# Generated by Django 5.0.2 on 2024-03-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oasisauth', '0002_pdffiles_patientrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='pfp',
            field=models.FileField(blank=True, null=True, upload_to='pfp/'),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='bloodGroup',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='pdf_files',
            field=models.ManyToManyField(blank=True, null=True, related_name='patient_records', to='oasisauth.pdffiles'),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
