# Generated by Django 5.0.2 on 2024-03-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oasisdoctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctord',
            name='pfp',
            field=models.ImageField(blank=True, null=True, upload_to='doctorPfp/'),
        ),
    ]
